#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///ssm_db?serverTimezone=UTC
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///ssm_db?serverTimezone=UTC
      username: root
      password: root

  main:
    banner-mode: off

#如果不写druid，但pom导入的druid坐标，starter依然会使用druid，pom没导入，会使用spring内嵌的hikari，hikari设置如下：
#spring:
#  datasource:
#    url: jdbc:mysql:///ssm_db?serverTimezone=UTC
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#url必须和hikari写在同一级



# 设置Mp相关配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
