#spring:
#  profiles:
#    active: dev
#    include: devMVC, devDB

# 以include加载，active最后加载，include按顺序加载，后加载会覆盖前面相同加载的

spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devMVC, devDB
      "pro": proMVC, proDB

# 以group加载，active首先加载，include按顺序加载，后加载会覆盖前面相同加载的


#debug: true
logging:
  # 设置分组
  group:
    ebank: com.meyok.controller, com.meyok.service, com.meyok.dao
    iservice : com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
#    com.meyok.controller: debug
    # 设置分组，对某个组设置日志级别
    ebank: warn
  # 设置日志格式
  pattern:
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
