server:
  port: 80

spring:
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: MeYok # \u914D\u7F6E\u5B58\u50A8\u961F\u5217\u540D
    pub-sub-domain: true # \u8868\u793A\u53D1\u5E03\u8BA2\u9605\u6A21\u578B\uFF0C\u9ED8\u8BA4\u70B9\u5BF9\u70B9\u6A21\u578B
